env:
 - GHCVER=7.4.2 CABALVER=1.18
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.2 CABALVER=1.20

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER hlint
 - cabal-$CABALVER update
 - cabal-$CABALVER install happy -j
 - export PATH=/opt/ghc/$GHCVER/bin:~/.cabal/bin:$PATH

install:
 - cabal-$CABALVER sandbox init
 - travis/github.sh ekmett/exceptions
 - travis/github.sh xich/temporary
 - cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks -j

script:
 - travis/script.sh
 - hlint src

matrix:
  fast_finish: true
